export { default as Letter0 } from './letter0.svg'
export { default as Letter1 } from './letter1.svg'
export { default as Letter2 } from './letter2.svg'
export { default as Letter3 } from './letter3.svg'
export { default as Letter4 } from './letter4.png'
export { default as Letter5 } from './letter5.png'
export { default as Letter6 } from './letter6.svg'
export { default as Letter7 } from './letter7.svg'
