export { default as Facebook } from './Facebook_Logo.webp'
export { default as LINE } from './Line_Logo.webp'
export { default as Kakao } from './Kakaotalk_Logo.webp'
export { default as X } from './X-Logo.webp'
export { default as Insta } from './Instagram_Logo.webp'
