export { default as Facebook } from './Facebook_Logo.png'
export { default as LINE } from './Line_Logo.png'
export { default as Kakao } from './Kakaotalk_Logo.png'
export { default as X } from './X-Logo.png'
export { default as Insta } from './Instagram_Logo.png'
